project_id = "rjmavtwxceztljclbtfj"

[functions.delete-wishlist]
verify_jwt = true

[functions.fetch-product-metadata]
verify_jwt = true

[functions.send-invitation]
verify_jwt = true

[functions.validate-invitation]
verify_jwt = false